Repository JEONG-J/Widi, pull requests merged in 2025-05, with the labels that each got.

#8 📝 [Docs]: README 업데이트
  README.md
Labels: :page_facing_up: Docs

#16 ➕ [Chore]: SPM 설치
  Widi/Widi.xcodeproj/project.pbxproj
Labels: :star: Important

#20 🎨 [Chore]: 파일 및 폴더 구조
  Widi/Widi/API/Service/WidiApp.swift
  Widi/Widi/App/AppFlowViewModel.swift
  Widi/Widi/App/AppleLoginManager.swift
  Widi/Widi/Common/Enum/TestEnum.swift
  Widi/Widi/Common/Protocol/TestProtocol.swift
  Widi/Widi/Common/UIComponents/Custom/TestCustom.swift
  Widi/Widi/Common/UIComponents/Diary/TestDiary.swift
  Widi/Widi/Common/UIComponents/Friends/TestFriends.swift
  Widi/Widi/Module/DetailDiary/ViewModels/DetailDiaryViewModel.swift
  Widi/Widi/Module/DetailDiary/Views/DetailDiaryView.swift
  Widi/Widi/Module/DetailFriends/ViewModels/DetailFriendsViewModel.swift
  Widi/Widi/Module/DetailFriends/Views/DetailFriendsView.swift
  Widi/Widi/Module/Home/ViewModels/HomeViewModels.swift
  Widi/Widi/Module/Home/Views/HomeView.swift
  Widi/Widi/Module/MyPage/ViewModels/MyPageViewModels.swift
  Widi/Widi/Module/MyPage/Views/MyPageView.swift
Labels: :sparkles: Feature, :star: Important

#36 💄 [Design]: 공용 커스텀 Alert 생성
  Widi/Widi/Common/Enum/AlertEnum.swift
  Widi/Widi/Common/Enum/TestEnum.swift
  Widi/Widi/Common/Protocol/ButtonTextProtocol.swift
  Widi/Widi/Common/Protocol/TestProtocol.swift
  Widi/Widi/Common/UIComponents/Custom/CustomAlert.swift
  Widi/Widi/Common/UIComponents/Custom/TestCustom.swift
Labels: :lipstick: UI
