Repository JEONG-J/Widi, pull requests merged in 2025-06, with the labels that each got.

#38 30 design 개인 컴포넌트 생성
  Widi/Widi/Common/Enum/AlertEnum.swift
  Widi/Widi/Common/Protocol/ButtonTextProtocol.swift
  Widi/Widi/Common/UIComponents/Custom/CustomAlert.swift
  Widi/Widi/Common/UIComponents/Diary/CalendarComponents.swift
  Widi/Widi/Common/UIComponents/Diary/CalendarViewModel.swift
  Widi/Widi/Common/UIComponents/Diary/Cell.swift
  Widi/Widi/Common/UIComponents/Diary/TestDiary.swift
  Widi/Widi/Common/UIComponents/Friends/FriendsAddButton.swift
  Widi/Widi/Common/UIComponents/Friends/FriendsCard.swift
  Widi/Widi/Common/UIComponents/Friends/TestFriends.swift
  Widi/Widi/Model/Cell/CellModel.swift
  Widi/Widi/Model/DTO/FriendAvatarDTO.swift
  Widi/Widi/Model/DTO/FriendDTO.swift
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Login/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Login/appleLoginButton.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Login/appleLoginButton.imageset/appleLoginButton.pdf
Labels: :lipstick: UI, :star: Important

#39 ✨ [Feat] 애플 로그인 기능 연결
  Widi/Widi/API/Service/AppleLoginManager.swift
  Widi/Widi/API/Service/Firebase/FirebaseAuthManager.swift
Labels: :globe_with_meridians: API, :sparkles: Feature

#41 💄 [Design] 일기 추가 버튼 생성
  Widi/Widi/Common/UIComponents/Diary/DiariesAddButton.swift
Labels: :lipstick: UI

#48 ♻️ [Refactor] CustomAlert 색상 변경
  Widi/Widi/Common/UIComponents/Custom/CustomAlert.swift
  Widi/Widi/Common/UIComponents/Diary/Calendar/CalendarComponents.swift
Labels: :hammer: Refactor

#50 ♻️ [Refactor] 여러가지 리팩 사항 추가
  Widi/Widi/Common/UIComponents/Custom/CustomAlert.swift
  Widi/Widi/Common/UIComponents/Diary/Calendar/CalendarComponents.swift
  Widi/Widi/Common/UIComponents/Diary/SelectedImagePreview.swift
  Widi/Widi/Resource/Modifier/ShadowModifier.swift
Labels: :hammer: Refactor

#44 💄 [Design] 마이페이지 SettingRow 생성
  Widi/Widi/Common/Enum/SettingRowEnum.swift
  Widi/Widi/Common/UIComponents/MyPage/SettingRow.swift
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Icon/chevronForward.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Icon/chevronForward.imageset/chevronForward.svg
  Widi/Widi/Resource/Font/Font.swift
Labels: :lipstick: UI

#46 💄 [Design] 친구 정보 요약 뷰( = FriendInfoView ) 생성
  Widi/Widi/Common/Enum/FriendInfoEnum.swift
  Widi/Widi/Common/UIComponents/Friends/FriendInfoView.swift
Labels: :lipstick: UI

#47 💄 [Design] 사진 페이지 인디케이터 생성
  Widi/Widi/Common/UIComponents/Diary/Picture/PicturePageIndicator.swift
Labels: :lipstick: UI

#54 52 design 커스텀 네비게이션 작성
  Widi/Widi/Common/Enum/Navi/NavigationBarConfig.swift
  Widi/Widi/Common/Enum/Navi/NavigationIcon.swift
  Widi/Widi/Common/UIComponents/Custom/Navi/CustomNavigation.swift
  Widi/Widi/Common/UIComponents/Custom/Navi/NaviIcon/CustomNavigation].swift
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviBack.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviBack.imageset/naviBack.pdf
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviClose.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviClose.imageset/naviClose.pdf
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviDelete.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviDelete.imageset/naviDelete.pdf
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviEdit.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviEdit.imageset/naviEdit.pdf
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviMore.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviMore.imageset/naviMore.pdf
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviSetting.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviSetting.imageset/naviSetting.png
Labels: :lipstick: UI, :sparkles: Feature

#55 53 design 마이페이지 뷰, 뷰모델 생성
  Widi/Widi/Module/MyPage/ViewModels/MyPageViewModels.swift
  Widi/Widi/Module/MyPage/Views/MyPageView.swift
Labels: :lipstick: UI

#58 56 design 문의하기 뷰 만들기
  Widi/Widi/App/WidiApp.swift
  Widi/Widi/Module/MyPage/Views/ContactUsView.swift
  Widi/Widi/Module/MyPage/Views/MyPageView.swift
Labels: :lipstick: UI

#70 💄 [Design] 친구 추가 작성 뷰
  Widi/Widi/App/WidiApp.swift
  Widi/Widi/Common/Enum/AddFriendsField.swift
  Widi/Widi/Common/Protocol/AddFriendsContent.swift
  Widi/Widi/Module/AddFriends/ViewModels/AddFriendsViewModel.swift
  Widi/Widi/Module/AddFriends/Views/AddFriendView.swift
Labels: :lipstick: UI

#71 💄 [Design] 텍스트 필드 예외처리
  Widi/Widi/Module/MyPage/ViewModels/ContactUsViewModel.swift
  Widi/Widi/Module/MyPage/ViewModels/MyPageViewModel.swift
  Widi/Widi/Module/MyPage/Views/ContactUsView.swift
  Widi/Widi/Module/MyPage/Views/MyPageView.swift
  Widi/Widi/Resource/Modifier/CustomTextEditor.swift
Labels: :lipstick: UI

#76 💄 [Design] 친구 추가 및 일기 생성 화면 구현
  Widi/Widi/App/WidiApp.swift
  Widi/Widi/Common/Enum/Navi/NavigationBarConfig.swift
  Widi/Widi/Common/UIComponents/Diary/Calendar/CalendarComponents.swift
  Widi/Widi/Common/UIComponents/Diary/DiaryKeyboardControl.swift
  Widi/Widi/Module/AddFriends/ViewModels/AddFriendsViewModel.swift
  Widi/Widi/Module/AddFriends/Views/AddDiaryView.swift
  Widi/Widi/Module/AddFriends/Views/AddFriendView.swift
  Widi/Widi/Module/AddFriends/Views/SheetCalendarView.swift
  Widi/Widi/Module/Home/Views/HomeDragView.swift
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Icon/album.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Icon/album.imageset/camera.pdf
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Icon/calendar.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Icon/calendar.imageset/calendar.pdf
  Widi/Widi/Resource/Assets Catalog/Color.xcassets/Etc/Contents.json
  Widi/Widi/Resource/Assets Catalog/Color.xcassets/Etc/bottomControl.colorset/Contents.json
Labels: :lipstick: UI

#75 💄 [Design] 문의하기 이메일 텍스트 필드 예외처리용 UI 만들기
  Widi/Widi/Module/MyPage/ViewModels/ContactUsViewModel.swift
  Widi/Widi/Module/MyPage/Views/ContactUsView.swift
  Widi/Widi/Module/MyPage/Views/MyPageView.swift
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Icon/error.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Icon/error.imageset/error.pdf
  Widi/Widi/Resource/Font/Font.swift
  Widi/Widi/Resource/Modifier/CustomTextEditor.swift
Labels: :lipstick: UI

#80 💄 [Design] 친구 정보 수정 뷰, 뷰모델 완료
  Widi/Widi/App/WidiApp.swift
  Widi/Widi/ContentView.swift
  Widi/Widi/Module/AddFriends/Views/AddFriendView.swift
  Widi/Widi/Module/DetailFriends/ViewModels/DetailFriendUpdateViewModel.swift
  Widi/Widi/Module/DetailFriends/Views/DetailFriendUpdateView.swift
  Widi/Widi/Module/MyPage/ViewModels/ContactUsViewModel.swift
  Widi/Widi/Resource/DataFormatter/DateFormatter.swift
Labels: :lipstick: UI

#84 ♻️ [Refactor] 일기 생성 뷰 수정
  Widi/Widi/Common/Enum/DiaryMode.swift
  Widi/Widi/Common/Protocol/DiaryViewModelProtocol.swift
  Widi/Widi/Common/UIComponents/Diary/SelectedImagePreview.swift
  Widi/Widi/Core/Navigation/NavigationRoutingView.swift
  Widi/Widi/Model/DTO/DiaryDTO.swift
  Widi/Widi/Module/AddFriends/ViewModels/AddFriendsViewModel.swift
  Widi/Widi/Module/AddFriends/Views/SheetCalendarView.swift
  Widi/Widi/Module/DetailDiary/ViewModels/DetailDiaryViewModel.swift
  Widi/Widi/Module/DetailDiary/Views/DetailDiaryView.swift
  Widi/Widi/Module/Diary/ViewModels/CreateDiaryViewModel.swift
  Widi/Widi/Module/Diary/ViewModels/DetailDiaryViewModel.swift
  Widi/Widi/Module/Diary/Views/AddDiaryView.swift
  Widi/Widi/Module/Diary/Views/DetailImageView.swift
  Widi/Widi/Module/Diary/Views/DiaryContainerView.swift
  Widi/Widi/Module/Diary/Views/DiaryImageScrollView.swift
  Widi/Widi/Module/SearchDiary/Views/SearchDiaryView.swift
  Widi/Widi/Resource/DataFormatter/ConvertDataFormat.swift
Labels: :hammer: Refactor, :lipstick: UI

#88 📝 [Docs]: README 업데이트
  README.md
  Widi/Widi/App/WidiApp.swift
  Widi/Widi/Common/UIComponents/Custom/Navi/CustomNavigation.swift
Labels: :page_facing_up: Docs

#95 ✨ [Feat] 앱 내부 네비게이션 연결
  Widi/Widi/Common/Enum/InfoAreatType.swift
  Widi/Widi/Core/Navigation/NavigationDestination.swift
  Widi/Widi/Core/Navigation/NavigationRoutingView.swift
  Widi/Widi/Module/DetailFriends/ViewModels/DetailFriendUpdateViewModel.swift
  Widi/Widi/Module/DetailFriends/ViewModels/DetailFriendsViewModel.swift
  Widi/Widi/Module/DetailFriends/Views/DetailFriendUpdateView.swift
  Widi/Widi/Module/DetailFriends/Views/DetailFriendsView.swift
  Widi/Widi/Module/Home/Views/HomeDragView.swift
  Widi/Widi/Module/Home/Views/HomeView.swift
  Widi/Widi/Module/MyPage/ViewModels/MyPageViewModel.swift
  Widi/Widi/Module/MyPage/Views/MyPageView.swift
  Widi/Widi/Module/SearchDiary/ViewModels/SearchDiaryViewModel.swift
  Widi/Widi/Module/SearchDiary/Views/SearchDiaryView.swift
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviSetting.imageset/Contents.json
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviSetting.imageset/naviSetting.pdf
  Widi/Widi/Resource/Assets Catalog/Assets.xcassets/Navi/naviSetting.imageset/naviSetting.png
Labels: :hammer: Refactor, :sparkles: Feature

#98 ♻️ [Refactor] 친구 상세 화면 뷰 수정 및 네비게이션
  Widi/Widi/Common/UIComponents/Diary/DiaryPreviewCard.swift
  Widi/Widi/Common/UIComponents/Diary/DiaryRowView.swift
  Widi/Widi/Core/Navigation/NavigationDestination.swift
  Widi/Widi/Core/Navigation/NavigationRoutingView.swift
  Widi/Widi/Module/AddFriends/ViewModels/AddFriendsViewModel.swift
  Widi/Widi/Module/DetailFriends/ViewModels/DetailFriendsViewModel.swift
  Widi/Widi/Module/DetailFriends/Views/DetailFriendsView.swift
  Widi/Widi/Module/Diary/Views/AddDiaryView.swift
Labels: :hammer: Refactor

#106 ✨ [Feat] 파이어베이스 연결
  Widi/Widi/API/Service/Firebase/FirebaseAuthManager.swift
  Widi/Widi/API/Service/Firebase/FirebaseDiaryService.swift
  Widi/Widi/API/Service/Firebase/FirebaseFriendsService.swift
  Widi/Widi/API/Service/FirebaseService.swift
  Widi/Widi/App/AppDelegate.swift
  Widi/Widi/Common/Enum/DiaryImage.swift
  Widi/Widi/Common/Enum/Error/LoginError.swift
  Widi/Widi/Common/Enum/FriendInfoEnum.swift
  Widi/Widi/Common/UIComponents/Custom/CustomProfileImage.swift
  Widi/Widi/Common/UIComponents/Diary/DiaryPreviewCard.swift
  Widi/Widi/Common/UIComponents/Friends/FriendInfoView.swift
  Widi/Widi/Common/UIComponents/Friends/FriendsCard.swift
  Widi/Widi/Core/Navigation/NavigationDestination.swift
  Widi/Widi/Core/Navigation/NavigationRoutingView.swift
  Widi/Widi/Model/DTO/DiaryDTO.swift
  Widi/Widi/Model/DTO/FriendAvatarDTO.swift
  Widi/Widi/Model/DTO/FriendDTO.swift
  Widi/Widi/Module/AddFriends/Views/AddFriendView.swift
  Widi/Widi/Module/DetailFriends/ViewModels/DetailFriendUpdateViewModel.swift
  Widi/Widi/Module/DetailFriends/ViewModels/DetailFriendsViewModel.swift
  Widi/Widi/Module/DetailFriends/Views/DetailFriendUpdateView.swift
  Widi/Widi/Module/DetailFriends/Views/DetailFriendsView.swift
  Widi/Widi/Module/Diary/ViewModels/CreateDiaryViewModel.swift
  Widi/Widi/Module/Diary/ViewModels/DetailDiaryViewModel.swift
  Widi/Widi/Module/Diary/Views/AddDiaryView.swift
  Widi/Widi/Module/Diary/Views/DetailDiaryScreenvView.swift
  Widi/Widi/Module/Home/ViewModels/HomeViewModel.swift
  Widi/Widi/Module/Home/Views/HomeDragView.swift
  Widi/Widi/Module/Login/ViewModels/LoginViewModel.swift
  Widi/Widi/Module/SearchDiary/ViewModels/SearchDiaryViewModel.swift
  Widi/Widi/Module/SearchDiary/Views/SearchDiaryView.swift
  Widi/Widi/Resource/Extension/asUIImage.swift
  Widi/Widi/Resource/Modifier/LoadingViewModifier.swift
Labels: :sparkles: Feature

#108 ✨ [Feat] FCM 토큰 연결
  Widi/Widi/API/Service/Firebase/FirebaseAuthManager.swift
  Widi/Widi/App/WidiApp.swift
Labels: :sparkles: Feature
